// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/calcular-diagnostico.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/features/diagnostico/engine/recomendacao.ts
var CONTEUDO = {
  atendimento: {
    titulo: "Agente de Atendimento",
    subtitulo: "Seu maior gargalo est\xE1 em responder clientes com velocidade e consist\xEAncia.",
    oQuePrecisa: `Um agente de atendimento automatiza respostas para as d\xFAvidas mais frequentes dos seus clientes \u2014 via WhatsApp, Instagram ou chat no site \u2014 sem precisar de um humano dispon\xEDvel 24h. Ele responde na hora, filtra o que precisa de aten\xE7\xE3o real e s\xF3 escala para voc\xEA o que n\xE3o consegue resolver. O resultado pr\xE1tico: menos tempo perdido em perguntas repetitivas e nenhum cliente ignorado por demora.`,
    ferramentas: [
      { nome: "Typebot", url: "https://typebot.io", descricao: "Fluxos de conversa visuais + WhatsApp", plano: "Gratuito" },
      { nome: "ManyChat", url: "https://manychat.com", descricao: "Automa\xE7\xE3o de DM no Instagram", plano: "Gratuito" },
      { nome: "Tidio", url: "https://tidio.com", descricao: "Chat com IA para sites", plano: "Gratuito" }
    ],
    ondeEncontrar: `Nenhuma dessas ferramentas exige programa\xE7\xE3o para come\xE7ar. A curva de aprendizado \xE9 de 1 a 2 semanas. Para integra\xE7\xE3o com WhatsApp, o Typebot \xE9 o ponto de entrada mais r\xE1pido no Brasil.`,
    comoComecar: `1. Liste as 10 perguntas que voc\xEA mais recebe dos clientes hoje (por WhatsApp, e-mail ou DM)
2. Escolha uma plataforma gratuita (Typebot ou ManyChat) e monte um fluxo respondendo s\xF3 essas 10 perguntas
3. Teste voc\xEA mesmo o fluxo como se fosse um cliente antes de ativar
4. Ative apenas para novos contatos e monitore por 7 dias antes de expandir

Voc\xEA n\xE3o precisa automatizar tudo de uma vez \u2014 comece pelo que mais repete.`,
    errosComuns: `- **Automatizar antes de mapear**: criar o bot sem saber quais perguntas chegam de verdade \u2192 o fluxo fica fora da realidade
- **Fluxo sem sa\xEDda humana**: bot que nunca transfere para uma pessoa \u2192 cliente preso em loop e frustrado
- **Linguagem rob\xF3tica**: mensagens formais demais ou gen\xE9ricas \u2192 queda de engajamento
- **N\xE3o monitorar**: ativar e esquecer \u2192 falhas acumulam sem que ningu\xE9m perceba`
  },
  vendas: {
    titulo: "Agente de Vendas e Follow-up",
    subtitulo: "Seu maior gargalo est\xE1 em manter o contato com leads quentes sem deixar oportunidade esfriar.",
    oQuePrecisa: `Um agente de vendas e follow-up automatiza a sequ\xEAncia de contatos com leads que j\xE1 demonstraram interesse \u2014 mandando a mensagem certa, no momento certo, sem depender da sua mem\xF3ria ou disponibilidade. Ele identifica quem parou de responder, reativa contatos frios e libera voc\xEA para focar nas negocia\xE7\xF5es que realmente precisam de aten\xE7\xE3o humana.`,
    ferramentas: [
      { nome: "RD Station CRM", url: "https://www.rdstation.com/crm/", descricao: "CRM brasileiro com follow-up", plano: "Gratuito" },
      { nome: "Kommo", url: "https://www.kommo.com", descricao: "Pipeline + automa\xE7\xE3o WhatsApp", plano: "Teste 14 dias" },
      { nome: "Pipedrive", url: "https://pipedrive.com", descricao: "Pipeline visual para times pequenos", plano: "Teste 14 dias" }
    ],
    ondeEncontrar: `Todas oferecem per\xEDodo de teste gratuito de 14 a 30 dias. Para times pequenos brasileiros que j\xE1 usam WhatsApp, o Kommo tem a integra\xE7\xE3o mais direta.`,
    comoComecar: `1. Mapeie seu funil atual: quais etapas existem do primeiro contato at\xE9 a venda fechada?
2. Identifique em qual etapa os leads param de responder (\xE9 aqui que o agente entra)
3. Crie uma sequ\xEAncia simples: contato inicial \u2192 follow-up em 48h \u2192 reativa\xE7\xE3o em 7 dias
4. Use um CRM com automa\xE7\xE3o (RD Station ou Kommo) para executar essa sequ\xEAncia sem interven\xE7\xE3o manual

Comece com 1 sequ\xEAncia, n\xE3o 10.`,
    errosComuns: `- **Follow-up gen\xE9rico**: mensagens iguais para todos os leads \u2192 baixa taxa de resposta
- **Frequ\xEAncia excessiva**: contatos di\xE1rios \u2192 lead marca como spam ou bloqueia
- **Sem contexto**: mensagem que n\xE3o referencia a conversa anterior \u2192 parece automa\xE7\xE3o \xF3bvia
- **Automatizar sem CRM**: usar planilha para controlar follow-up \u2192 inevitavelmente perde contatos`
  },
  operacao: {
    titulo: "Agente de Automa\xE7\xE3o e Opera\xE7\xE3o",
    subtitulo: "Seu maior gargalo est\xE1 em tarefas repetitivas internas que consomem tempo sem gerar valor direto.",
    oQuePrecisa: `Um agente de automa\xE7\xE3o operacional conecta sistemas, move dados entre ferramentas e executa tarefas repetitivas sem precisar de ningu\xE9m para apertar o bot\xE3o. Relat\xF3rios que voc\xEA gera manualmente toda semana, notifica\xE7\xF5es que voc\xEA envia por fora, dados que voc\xEA copia de uma planilha para outra \u2014 tudo isso pode rodar sozinho, em hor\xE1rio programado ou acionado por um evento.`,
    ferramentas: [
      { nome: "Make", url: "https://make.com", descricao: "Automa\xE7\xE3o visual entre centenas de apps", plano: "Gr\xE1tis 1k ops/m\xEAs" },
      { nome: "n8n", url: "https://n8n.io", descricao: "Open source, sem limite de opera\xE7\xF5es", plano: "Open source" },
      { nome: "Zapier", url: "https://zapier.com", descricao: "+6.000 integra\xE7\xF5es, o mais popular", plano: "Gr\xE1tis 100 tasks" }
    ],
    ondeEncontrar: `Para come\xE7ar sem programa\xE7\xE3o, Make ou Zapier s\xE3o os mais acess\xEDveis. O n8n \xE9 ideal para quem quer controle total sem pagar por uso.`,
    comoComecar: `1. Escolha UMA tarefa repetitiva que voc\xEA faz toda semana (ex: gerar relat\xF3rio, enviar confirma\xE7\xE3o, mover dados entre planilhas)
2. Mapeie o passo a passo manual dessa tarefa (quais apps envolvidos, em que ordem)
3. Crie um fluxo no Make ou Zapier replicando esses passos
4. Rode o fluxo em paralelo com o processo manual por 1 semana antes de desligar o manual

Automatize uma tarefa de cada vez. Complexidade acumulada quebra tudo.`,
    errosComuns: `- **Automatizar processo quebrado**: se o processo manual j\xE1 tem falhas, a automa\xE7\xE3o vai replic\xE1-las em escala
- **Depend\xEAncia de planilha como banco de dados**: Google Sheets como fonte de dados de automa\xE7\xE3o \u2192 inst\xE1vel e lento
- **Sem tratamento de erro**: automa\xE7\xE3o que n\xE3o notifica quando falha \u2192 problema silencioso por dias
- **Over-engineering**: criar fluxo complexo para problema que um lembrete no celular resolveria`
  },
  financeiro: {
    titulo: "Agente Financeiro",
    subtitulo: "Seu maior gargalo est\xE1 na previsibilidade de caixa e na cobran\xE7a manual de clientes.",
    oQuePrecisa: `Um agente financeiro automatiza o envio de cobran\xE7as, lembretes de pagamento e concilia\xE7\xE3o b\xE1sica de receb\xEDveis \u2014 eliminando o trabalho de perseguir clientes inadimplentes manualmente e dando visibilidade real sobre o que entra e quando. N\xE3o substitui um contador, mas resolve o operacional financeiro que hoje consome seu tempo.`,
    ferramentas: [
      { nome: "Asaas", url: "https://asaas.com", descricao: "Cobran\xE7as autom\xE1ticas: boleto, PIX, cart\xE3o", plano: "Gratuito" },
      { nome: "Vindi", url: "https://vindi.com.br", descricao: "Recorr\xEAncia e mensalidades", plano: "Sob consulta" },
      { nome: "Conta Simples", url: "https://contasimples.com", descricao: "Conta PJ + categoriza\xE7\xE3o autom\xE1tica", plano: "Gratuito" }
    ],
    ondeEncontrar: `Para cobran\xE7a autom\xE1tica no Brasil, o Asaas \xE9 o ponto de entrada mais direto \u2014 tem plano gratuito, aceita PIX, boleto e cart\xE3o, e j\xE1 inclui r\xE9gua de cobran\xE7a embutida.`,
    comoComecar: `1. Liste todos os clientes que te devem hoje e o status de cada cobran\xE7a
2. Crie uma conta no Asaas (gratuito) e importe esses clientes
3. Configure uma r\xE9gua de cobran\xE7a: lembrete 3 dias antes do vencimento + no dia + 3 dias depois
4. Ative o PIX autom\xE1tico para novos clientes e monitore o primeiro ciclo completo

A r\xE9gua de cobran\xE7a sozinha j\xE1 elimina boa parte do trabalho manual.`,
    errosComuns: `- **Cobran\xE7a agressiva sem relacionamento**: mensagens autom\xE1ticas frias \u2192 deteriora a rela\xE7\xE3o com o cliente
- **N\xE3o categorizar despesas**: receber bem mas n\xE3o saber onde gasta \u2192 caixa positivo com surpresas no fim do m\xEAs
- **Previs\xE3o de caixa por planilha**: atualiza\xE7\xE3o manual \u2192 sempre desatualizada na hora que precisa
- **Ignorar inadimpl\xEAncia at\xE9 virar problema**: sem r\xE9gua \u2192 percebe s\xF3 quando o fluxo j\xE1 est\xE1 comprometido`
  }
};
var P1_MAP = {
  "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho": "atendimento",
  "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade": "vendas",
  "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva": "operacao",
  "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual": "financeiro"
};
var NOME_CATEGORIA = {
  atendimento: "atendimento",
  vendas: "vendas e follow-up",
  operacao: "opera\xE7\xE3o interna",
  financeiro: "financeiro"
};
var PONTE_META = {
  atendimento: "Um agente de atendimento \xE9 o caminho mais curto at\xE9 l\xE1 \u2014 libera as horas que hoje somem respondendo o mesmo tipo de mensagem.",
  vendas: "Um agente de follow-up encurta esse caminho \u2014 mant\xE9m o contato quente sem depender da sua mem\xF3ria, para voc\xEA chegar l\xE1 com pipeline cheio.",
  operacao: "Automatizar opera\xE7\xE3o libera exatamente as horas semanais que hoje somem no repetitivo \u2014 \xE9 o que te tira de operador para dono.",
  financeiro: "Um agente financeiro cria previsibilidade \u2014 sem isso, essa meta fica sempre a um m\xEAs de dist\xE2ncia."
};
function truncar(texto, max) {
  const limpo = texto.trim();
  return limpo.length > max ? `${limpo.slice(0, max).trimEnd()}\u2026` : limpo;
}
function classificarPerfil(p5) {
  if (p5 === "Sim, testei mas n\xE3o deu certo") return "testou-falhou";
  if (p5 === "Sim, uso algo hoje mas quero melhorar") return "ja-usa";
  return "iniciante";
}
var INTRO_PERFIL = {
  iniciante: `Como \xE9 sua primeira vez com IA, comece pelo mais simples poss\xEDvel \u2014 resista ao impulso de montar tudo de uma vez. O objetivo das primeiras 2 semanas \xE9 entender a ferramenta funcionando de verdade, n\xE3o impressionar ningu\xE9m.

`,
  "testou-falhou": `J\xE1 que uma tentativa anterior n\xE3o deu certo, o ponto de virada aqui \xE9 escopo: rode um \xFAnico caso de uso ponta a ponta antes de expandir. A maioria das tentativas falha por tentar automatizar cedo demais, coisas demais.

`,
  "ja-usa": `Como voc\xEA j\xE1 usa alguma coisa hoje, foque em integra\xE7\xE3o e evolu\xE7\xE3o do que existe \u2014 n\xE3o em recome\xE7ar. Mapeie onde a ferramenta atual entrega valor e onde ela para, e trate esse gap como o pr\xF3ximo agente.

`
};
function calcularResultado(respostas) {
  const p1 = respostas[1] ?? "";
  const p2 = respostas[2] ?? "";
  const p3 = respostas[3] ?? "";
  const p4 = respostas[4] ?? "";
  const p5 = respostas[5] ?? "";
  const p6 = respostas[6] ?? "";
  const categoriaOriginal = P1_MAP[p1] ?? "atendimento";
  let categoria = categoriaOriginal;
  const timeMinimo = p2 === "S\xF3 eu" || p2 === "2 a 5 pessoas";
  const altaVolume = p3 === "Mais de 50";
  const overrideAtendimento = timeMinimo && altaVolume && categoriaOriginal !== "atendimento";
  if (overrideAtendimento) categoria = "atendimento";
  const perfilExperiencia = classificarPerfil(p5);
  const avisoToolsGenericas = perfilExperiencia === "testou-falhou";
  const conteudo = CONTEUDO[categoria];
  const contextoTime = {
    "S\xF3 eu": "Trabalhando sozinho, cada hora gasta em tarefa repetitiva \xE9 uma hora que voc\xEA n\xE3o gasta crescendo o neg\xF3cio",
    "2 a 5 pessoas": "Com um time enxuto de 2 a 5 pessoas, voc\xEA n\xE3o tem folga para alocar algu\xE9m s\xF3 nisso",
    "6 a 20 pessoas": "Com 6 a 20 pessoas, o custo de manter isso manual j\xE1 pesa na folha e no ritmo da equipe",
    "Mais de 20 pessoas": "Com mais de 20 pessoas, processos manuais viram gargalo de coordena\xE7\xE3o e erro em escala"
  };
  const contextoVolume = {
    "Menos de 10": "Mesmo com menos de 10 contatos por dia, a inconsist\xEAncia \xE9 o que custa cliente",
    "Entre 10 e 50": "Com 10 a 50 contatos por dia, voc\xEA j\xE1 est\xE1 no volume em que o manual come\xE7a a vazar",
    "Mais de 50": "Com mais de 50 contatos por dia, \xE9 humanamente imposs\xEDvel manter qualidade sem automa\xE7\xE3o"
  };
  const fraseTime = contextoTime[p2] ?? "";
  const fraseVolume = contextoVolume[p3] ?? "";
  const p4Curto = truncar(p4, 120);
  const tarefa = p4Curto ? ` Voc\xEA destacou "${p4Curto}" como a tarefa que mais consome seu tempo \u2014 exatamente o tipo de coisa que esse agente elimina.` : "";
  const porqueBase = {
    atendimento: `O ponto cr\xEDtico est\xE1 na velocidade e consist\xEAncia do atendimento. ${fraseVolume || fraseTime || "Perder clientes por demora de resposta \xE9 resolv\xEDvel com automa\xE7\xE3o focada"}.`,
    vendas: `O gargalo est\xE1 no acompanhamento de oportunidades que j\xE1 existem. Leads sem resposta por mais de 24h t\xEAm chance de convers\xE3o drasticamente menor. ${fraseTime || fraseVolume || "Um agente de follow-up resolve isso sem depender de mem\xF3ria"}.`,
    operacao: `O tempo perdido em processos manuais internos \xE9 o maior freio de crescimento. ${fraseTime || fraseVolume || "Automatizar opera\xE7\xE3o libera horas semanais para o trabalho que precisa de voc\xEA"}.`,
    financeiro: `A falta de previsibilidade de caixa e a cobran\xE7a manual s\xE3o os maiores riscos para a sa\xFAde do neg\xF3cio. ${fraseTime || "Um agente financeiro resolve o operacional e d\xE1 clareza sobre o que entra e quando"}.`
  };
  let prefacio = "";
  if (overrideAtendimento) {
    const gargaloTexto = NOME_CATEGORIA[categoriaOriginal];
    prefacio = `Voc\xEA marcou ${gargaloTexto} como gargalo, mas com ${p2.toLowerCase()} e ${p3.toLowerCase()} contatos por dia, o atendimento vira o freio real antes de qualquer outra coisa \u2014 por isso o diagn\xF3stico foi ajustado. `;
  }
  const porque = `${prefacio}${porqueBase[categoria]}${tarefa}`;
  const metaTresMeses = truncar(p6, 220);
  const pontePessoal = PONTE_META[categoria];
  const comoComecar = `${INTRO_PERFIL[perfilExperiencia]}${conteudo.comoComecar}`;
  return {
    categoria,
    ...conteudo,
    comoComecar,
    porque,
    avisoToolsGenericas,
    perfilExperiencia,
    metaTresMeses,
    pontePessoal
  };
}

// src/lib/mcp/tools/calcular-diagnostico.ts
var P1 = z.enum([
  "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
]);
var P2 = z.enum(["S\xF3 eu", "2 a 5 pessoas", "6 a 20 pessoas", "Mais de 20 pessoas"]);
var P3 = z.enum(["Menos de 10", "Entre 10 e 50", "Mais de 50"]);
var P5 = z.enum([
  "N\xE3o, seria minha primeira vez",
  "Sim, testei mas n\xE3o deu certo",
  "Sim, uso algo hoje mas quero melhorar"
]);
var calcular_diagnostico_default = defineTool({
  name: "calcular_diagnostico",
  title: "Calcular diagn\xF3stico de agente de IA",
  description: "Roda o motor de recomenda\xE7\xE3o do Focus Diagn\xF3stico e retorna qual tipo de agente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) o neg\xF3cio deve priorizar, com justificativa, ferramentas recomendadas e guia de implementa\xE7\xE3o.",
  inputSchema: {
    gargalo_principal: P1.describe("Resposta da pergunta 1: onde est\xE1 o maior gargalo do neg\xF3cio."),
    tamanho_time: P2.describe("Resposta da pergunta 2: tamanho do time."),
    volume_contatos_dia: P3.describe("Resposta da pergunta 3: volume de contatos por dia."),
    tarefa_que_mais_consome: z.string().min(1).max(200).describe("Resposta da pergunta 4: tarefa manual que mais consome tempo (texto livre)."),
    ja_tentou_automatizar: P5.describe("Resposta da pergunta 5: hist\xF3rico de tentativas com automa\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const respostas = {
      1: input.gargalo_principal,
      2: input.tamanho_time,
      3: input.volume_contatos_dia,
      4: input.tarefa_que_mais_consome,
      5: input.ja_tentou_automatizar
    };
    const resultado = calcularResultado(respostas);
    return {
      content: [{ type: "text", text: JSON.stringify(resultado, null, 2) }],
      structuredContent: { resultado }
    };
  }
});

// src/lib/mcp/tools/listar-ferramentas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var CATEGORIAS = ["atendimento", "vendas", "operacao", "financeiro"];
var GARGALO_POR_CATEGORIA = {
  atendimento: "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  vendas: "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  operacao: "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  financeiro: "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
};
var listar_ferramentas_default = defineTool2({
  name: "listar_ferramentas_por_categoria",
  title: "Listar ferramentas por categoria de agente",
  description: "Retorna as ferramentas recomendadas (nome, URL, descri\xE7\xE3o, plano) para uma categoria de agente de IA: atendimento, vendas, opera\xE7\xE3o ou financeiro.",
  inputSchema: {
    categoria: z2.enum(CATEGORIAS).describe("Categoria do agente de IA.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoria }) => {
    const resultado = calcularResultado({
      1: GARGALO_POR_CATEGORIA[categoria],
      2: "2 a 5 pessoas",
      3: "Entre 10 e 50",
      4: "tarefas repetitivas",
      5: "N\xE3o, nunca tentei"
    });
    const payload = {
      categoria,
      titulo: resultado.titulo,
      ferramentas: resultado.ferramentas,
      ondeEncontrar: resultado.ondeEncontrar
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "focus-diagnostico-mcp",
  title: "Focus Diagn\xF3stico \u2014 Agentes de IA",
  version: "0.1.0",
  instructions: "Ferramentas do Focus Diagn\xF3stico. Use `calcular_diagnostico` para descobrir qual tipo de agente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) um neg\xF3cio deve priorizar, dadas as 5 respostas do diagn\xF3stico. Use `listar_ferramentas_por_categoria` para obter ferramentas recomendadas em uma categoria espec\xEDfica.",
  tools: [calcular_diagnostico_default, listar_ferramentas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
