// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/calcular-diagnostico.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/features/diagnostico/engine/recomendacao.ts
var PERFIL_LABEL = {
  autonomo: "aut\xF4nomo / freelancer",
  consultor: "consultor",
  agencia: "ag\xEAncia",
  empresa: "empresa com time"
};
var PERFIL_MAP = {
  "Aut\xF4nomo ou freelancer \u2014 sou eu que fa\xE7o e entrego": "autonomo",
  "Consultor \u2014 presto servi\xE7o recorrente pra alguns clientes": "consultor",
  "Ag\xEAncia \u2014 tenho um time entregando pra v\xE1rios clientes": "agencia",
  "Empresa com time \u2014 opera\xE7\xE3o interna com funcion\xE1rios": "empresa"
};
function classificarPerfil(resposta) {
  return PERFIL_MAP[resposta] ?? "empresa";
}
var NOME_AGENTE = {
  atendimento: "Agente de Atendimento",
  vendas: "Agente de Vendas e Follow-up",
  operacao: "Agente de Automa\xE7\xE3o e Opera\xE7\xE3o",
  financeiro: "Agente Financeiro"
};
var NOME_FRENTE = {
  atendimento: "atendimento ao cliente",
  vendas: "vendas e follow-up",
  operacao: "opera\xE7\xE3o interna",
  financeiro: "gest\xE3o financeira"
};
var SUBTITULO = {
  atendimento: "Seu maior gargalo est\xE1 em responder clientes com velocidade e consist\xEAncia.",
  vendas: "Seu maior gargalo est\xE1 em manter o contato com leads quentes sem deixar oportunidade esfriar.",
  operacao: "Seu maior gargalo est\xE1 em tarefas repetitivas internas que consomem tempo sem gerar valor direto.",
  financeiro: "Seu maior gargalo est\xE1 na previsibilidade de caixa e na cobran\xE7a manual de clientes."
};
var CONTEUDO = {
  atendimento: {
    oQuePrecisa: `Um agente de atendimento automatiza respostas para as d\xFAvidas mais frequentes dos seus clientes \u2014 via WhatsApp, Instagram ou chat no site \u2014 sem precisar de um humano dispon\xEDvel 24h. Ele responde na hora, filtra o que precisa de aten\xE7\xE3o real e s\xF3 escala para voc\xEA o que n\xE3o consegue resolver. O resultado pr\xE1tico: menos tempo perdido em perguntas repetitivas e nenhum cliente ignorado por demora.`,
    ferramentas: [
      { nome: "Typebot", url: "https://typebot.io", descricao: "Fluxos de conversa visuais + WhatsApp", plano: "Gratuito" },
      { nome: "ManyChat", url: "https://manychat.com", descricao: "Automa\xE7\xE3o de DM no Instagram", plano: "Gratuito" },
      { nome: "Tidio", url: "https://tidio.com", descricao: "Chat com IA para sites", plano: "Gratuito" }
    ],
    ondeEncontrar: `Nenhuma dessas ferramentas exige programa\xE7\xE3o para come\xE7ar. A curva de aprendizado \xE9 de 1 a 2 semanas. Para integra\xE7\xE3o com WhatsApp, o Typebot \xE9 o ponto de entrada mais r\xE1pido no Brasil.`,
    comoComecar: `1. Liste as 10 perguntas que voc\xEA mais recebe dos clientes hoje (por WhatsApp, e-mail ou DM)
2. Escolha uma plataforma gratuita (Typebot ou ManyChat) e monte um fluxo respondendo s\xF3 essas 10 perguntas
3. Teste voc\xEA mesmo o fluxo como se fosse um cliente antes de ativar
4. Ative apenas para novos contatos e monitore por 7 dias antes de expandir

Voc\xEA n\xE3o precisa automatizar tudo de uma vez \u2014 comece pelo que mais repete.`,
    errosComuns: `- **Automatizar antes de mapear**: criar o bot sem saber quais perguntas chegam de verdade \u2192 o fluxo fica fora da realidade
- **Fluxo sem sa\xEDda humana**: bot que nunca transfere para uma pessoa \u2192 cliente preso em loop e frustrado
- **Linguagem rob\xF3tica**: mensagens formais demais ou gen\xE9ricas \u2192 queda de engajamento
- **N\xE3o monitorar**: ativar e esquecer \u2192 falhas acumulam sem que ningu\xE9m perceba`
  },
  vendas: {
    oQuePrecisa: `Um agente de vendas e follow-up automatiza a sequ\xEAncia de contatos com leads que j\xE1 demonstraram interesse \u2014 mandando a mensagem certa, no momento certo, sem depender da sua mem\xF3ria ou disponibilidade. Ele identifica quem parou de responder, reativa contatos frios e libera voc\xEA para focar nas negocia\xE7\xF5es que realmente precisam de aten\xE7\xE3o humana.`,
    ferramentas: [
      { nome: "RD Station CRM", url: "https://www.rdstation.com/crm/", descricao: "CRM brasileiro com follow-up", plano: "Gratuito" },
      { nome: "Kommo", url: "https://www.kommo.com", descricao: "Pipeline + automa\xE7\xE3o WhatsApp", plano: "Teste 14 dias" },
      { nome: "Pipedrive", url: "https://pipedrive.com", descricao: "Pipeline visual para times pequenos", plano: "Teste 14 dias" }
    ],
    ondeEncontrar: `Todas oferecem per\xEDodo de teste gratuito de 14 a 30 dias. Para times pequenos brasileiros que j\xE1 usam WhatsApp, o Kommo tem a integra\xE7\xE3o mais direta.`,
    comoComecar: `1. Mapeie seu funil atual: quais etapas existem do primeiro contato at\xE9 a venda fechada?
2. Identifique em qual etapa os leads param de responder (\xE9 aqui que o agente entra)
3. Crie uma sequ\xEAncia simples: contato inicial \u2192 follow-up em 48h \u2192 reativa\xE7\xE3o em 7 dias
4. Use um CRM com automa\xE7\xE3o (RD Station ou Kommo) para executar essa sequ\xEAncia sem interven\xE7\xE3o manual

Comece com 1 sequ\xEAncia, n\xE3o 10.`,
    errosComuns: `- **Follow-up gen\xE9rico**: mensagens iguais para todos os leads \u2192 baixa taxa de resposta
- **Frequ\xEAncia excessiva**: contatos di\xE1rios \u2192 lead marca como spam ou bloqueia
- **Sem contexto**: mensagem que n\xE3o referencia a conversa anterior \u2192 parece automa\xE7\xE3o \xF3bvia
- **Automatizar sem CRM**: usar planilha para controlar follow-up \u2192 inevitavelmente perde contatos`
  },
  operacao: {
    oQuePrecisa: `Um agente de automa\xE7\xE3o operacional conecta sistemas, move dados entre ferramentas e executa tarefas repetitivas sem precisar de ningu\xE9m para apertar o bot\xE3o. Relat\xF3rios que voc\xEA gera manualmente toda semana, notifica\xE7\xF5es que voc\xEA envia por fora, dados que voc\xEA copia de uma planilha para outra \u2014 tudo isso pode rodar sozinho, em hor\xE1rio programado ou acionado por um evento.`,
    ferramentas: [
      { nome: "Make", url: "https://make.com", descricao: "Automa\xE7\xE3o visual entre centenas de apps", plano: "Gr\xE1tis 1k ops/m\xEAs" },
      { nome: "n8n", url: "https://n8n.io", descricao: "Open source, sem limite de opera\xE7\xF5es", plano: "Open source" },
      { nome: "Zapier", url: "https://zapier.com", descricao: "+6.000 integra\xE7\xF5es, o mais popular", plano: "Gr\xE1tis 100 tasks" }
    ],
    ondeEncontrar: `Para come\xE7ar sem programa\xE7\xE3o, Make ou Zapier s\xE3o os mais acess\xEDveis. O n8n \xE9 ideal para quem quer controle total sem pagar por uso.`,
    comoComecar: `1. Escolha UMA tarefa repetitiva que voc\xEA faz toda semana (ex: gerar relat\xF3rio, enviar confirma\xE7\xE3o, mover dados entre planilhas)
2. Mapeie o passo a passo manual dessa tarefa (quais apps envolvidos, em que ordem)
3. Crie um fluxo no Make ou Zapier replicando esses passos
4. Rode o fluxo em paralelo com o processo manual por 1 semana antes de desligar o manual

Automatize uma tarefa de cada vez. Complexidade acumulada quebra tudo.`,
    errosComuns: `- **Automatizar processo quebrado**: se o processo manual j\xE1 tem falhas, a automa\xE7\xE3o vai replic\xE1-las em escala
- **Depend\xEAncia de planilha como banco de dados**: Google Sheets como fonte de dados de automa\xE7\xE3o \u2192 inst\xE1vel e lento
- **Sem tratamento de erro**: automa\xE7\xE3o que n\xE3o notifica quando falha \u2192 problema silencioso por dias
- **Over-engineering**: criar fluxo complexo para problema que um lembrete no celular resolveria`
  },
  financeiro: {
    oQuePrecisa: `Um agente financeiro automatiza o envio de cobran\xE7as, lembretes de pagamento e concilia\xE7\xE3o b\xE1sica de receb\xEDveis \u2014 eliminando o trabalho de perseguir clientes inadimplentes manualmente e dando visibilidade real sobre o que entra e quando. N\xE3o substitui um contador, mas resolve o operacional financeiro que hoje consome seu tempo.`,
    ferramentas: [
      { nome: "Asaas", url: "https://asaas.com", descricao: "Cobran\xE7as autom\xE1ticas: boleto, PIX, cart\xE3o", plano: "Gratuito" },
      { nome: "Vindi", url: "https://vindi.com.br", descricao: "Recorr\xEAncia e mensalidades", plano: "Sob consulta" },
      { nome: "Conta Simples", url: "https://contasimples.com", descricao: "Conta PJ + categoriza\xE7\xE3o autom\xE1tica", plano: "Gratuito" }
    ],
    ondeEncontrar: `Para cobran\xE7a autom\xE1tica no Brasil, o Asaas \xE9 o ponto de entrada mais direto \u2014 tem plano gratuito, aceita PIX, boleto e cart\xE3o, e j\xE1 inclui r\xE9gua de cobran\xE7a embutida.`,
    comoComecar: `1. Liste todos os clientes que te devem hoje e o status de cada cobran\xE7a
2. Crie uma conta no Asaas (gratuito) e importe esses clientes
3. Configure uma r\xE9gua de cobran\xE7a: lembrete 3 dias antes do vencimento + no dia + 3 dias depois
4. Ative o PIX autom\xE1tico para novos clientes e monitore o primeiro ciclo completo

A r\xE9gua de cobran\xE7a sozinha j\xE1 elimina boa parte do trabalho manual.`,
    errosComuns: `- **Cobran\xE7a agressiva sem relacionamento**: mensagens autom\xE1ticas frias \u2192 deteriora a rela\xE7\xE3o com o cliente
- **N\xE3o categorizar despesas**: receber bem mas n\xE3o saber onde gasta \u2192 caixa positivo com surpresas no fim do m\xEAs
- **Previs\xE3o de caixa por planilha**: atualiza\xE7\xE3o manual \u2192 sempre desatualizada na hora que precisa
- **Ignorar inadimpl\xEAncia at\xE9 virar problema**: sem r\xE9gua \u2192 percebe s\xF3 quando o fluxo j\xE1 est\xE1 comprometido`
  }
};
var P1_MAP = {
  "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho": "atendimento",
  "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade": "vendas",
  "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva": "operacao",
  "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual": "financeiro"
};
var NOME_CATEGORIA = {
  atendimento: "atendimento",
  vendas: "vendas e follow-up",
  operacao: "opera\xE7\xE3o interna",
  financeiro: "financeiro"
};
var PONTE_META = {
  atendimento: "Um agente de atendimento \xE9 o caminho mais curto at\xE9 l\xE1 \u2014 libera as horas que hoje somem respondendo o mesmo tipo de mensagem.",
  vendas: "Um agente de follow-up encurta esse caminho \u2014 mant\xE9m o contato quente sem depender da sua mem\xF3ria, para voc\xEA chegar l\xE1 com pipeline cheio.",
  operacao: "Automatizar opera\xE7\xE3o libera exatamente as horas semanais que hoje somem no repetitivo \u2014 \xE9 o que te tira de operador para dono.",
  financeiro: "Um agente financeiro cria previsibilidade \u2014 sem isso, essa meta fica sempre a um m\xEAs de dist\xE2ncia."
};
var KEYWORDS = {
  atendimento: [
    /respond/i,
    /atend/i,
    /client/i,
    /whats?app/i,
    /instagram|dm\b|direct/i,
    /d[uú]vida/i,
    /suporte/i,
    /chat/i,
    /mensagem/i
  ],
  vendas: [
    /lead/i,
    /follow[- ]?up/i,
    /proposta/i,
    /or[çc]amento/i,
    /cotar|cota[çc][aã]o/i,
    /vend/i,
    /prospect/i,
    /cobrar resposta/i,
    /fechar/i,
    /pipeline|funil/i
  ],
  operacao: [
    /planilha/i,
    /relat[oó]rio/i,
    /cadastr/i,
    /copiar|copio|copia/i,
    /processo/i,
    /repetitiv/i,
    /dado|dados/i,
    /import(a|ar)/i,
    /export(a|ar)/i,
    /integr/i,
    /nota fiscal|nfe/i
  ],
  financeiro: [
    /cobran[çc]/i,
    /boleto/i,
    /pix/i,
    /caixa/i,
    /inadimpl/i,
    /fluxo de caixa/i,
    /fatura/i,
    /pag(a|amento)/i,
    /recebiv/i,
    /financ/i,
    /conta[s]? a (pagar|receber)/i
  ]
};
function truncar(texto, max) {
  const limpo = texto.trim();
  return limpo.length > max ? `${limpo.slice(0, max).trimEnd()}\u2026` : limpo;
}
function metaValida(texto) {
  const s = (texto ?? "").trim().toLowerCase();
  if (s.length < 12) return false;
  if (/^(sei l[aá]|n[aã]o sei|nao sei|n sei|talvez|qualquer|nada|nenhuma|tanto faz|-+|\.+|x+)$/.test(s)) return false;
  if (!/\s/.test(s)) return false;
  const palavras = s.split(/\s+/).filter((w) => w.length > 2);
  return palavras.length >= 3;
}
function classificarExperiencia(jaUsaRaw) {
  const s = (jaUsaRaw ?? "").toLowerCase();
  if (/n[aã]o engatou|testei.*n[aã]o|desisti/.test(s)) return "testou-falhou";
  if (!s.trim() || /nada ainda|primeira vez/.test(s)) return "iniciante";
  return "ja-usa";
}
function parseJaUsa(jaUsaRaw) {
  return (jaUsaRaw ?? "").split(/\s*[;|]\s*/).map((s) => s.trim()).filter(Boolean).filter((s) => !/nada ainda|primeira vez|n[aã]o engatou/i.test(s));
}
var GRUPO_JA_USA = {
  atendimento: /chatbot|atendimento|manychat|typebot|tidio/i,
  vendas: /\bcrm\b|rd station|pipedrive|hubspot|kommo/i,
  operacao: /automa[çc][aã]o|\bmake\b|zapier|n8n/i,
  financeiro: /cobran[çc]a|asaas|cora|vindi/i,
  iaGeral: /chatgpt|gemini|claude|copilot/i,
  planilha: /planilha|sheets|excel/i
};
function usaGrupo(jaUsa, grupo) {
  return jaUsa.some((s) => GRUPO_JA_USA[grupo].test(s));
}
var SUB_FRENTES_KW = {
  atendimento: [
    { id: "instagram-dm", kw: /instagram|\bdm\b|direct|coment[aá]rio|stories?/i, grupo: "atendimento" },
    { id: "site-chat", kw: /\bsite\b|website|p[aá]gina|landing|\bloja\b|e-?commerce|checkout/i, grupo: "atendimento" },
    { id: "multicanal", kw: /v[aá]rios canais|multicanal|caixa de entrada|\binbox\b|time atende|equipe atende|central de atendimento/i, grupo: "atendimento" },
    { id: "whatsapp-faq", kw: /whats?app|\bzap\b|d[uú]vida|pergunta|\bfaq\b|hor[aá]rio/i, grupo: "atendimento" }
  ],
  vendas: [
    { id: "email-sequencia", kw: /e-?mail|newsletter|nutri[çc][aã]o|sequ[eê]ncia|disparo|cad[eê]ncia|marketing|autom[aá]tico de e-?mail|automatizar.*e-?mail/i, grupo: null },
    { id: "proposta", kw: /proposta|or[çc]amento|cota[çc][aã]o|contrato|escopo|apresenta[çc][aã]o comercial/i, grupo: "iaGeral" },
    { id: "followup-whatsapp", kw: /whats?app|\bzap\b|cobrar resposta|retomar|reativar|lembrar de responder/i, grupo: "vendas" },
    { id: "organizar-funil", kw: /funil|pipeline|perco (lead|cliente|oportunidade)|organizar|planilha de vendas|esque[çc]o|acompanhar|controle/i, grupo: "vendas" }
  ],
  operacao: [
    { id: "base-dados", kw: /planilha|base de dados|cadastro|\bcaos\b|v[aá]rias abas|controle em excel/i, grupo: "planilha" },
    { id: "documento", kw: /relat[oó]rio|documento|\bata\b|resumo|descri[çc][aã]o|texto|apresenta[çc][aã]o/i, grupo: "iaGeral" },
    { id: "tecnico", kw: /open source|c[oó]digo|\bapi\b|sem limite|volume alto|self-?host|desenvolvedor|customiza/i, grupo: "operacao" },
    { id: "automatizar", kw: /automa[çc]|integr|conectar|mover dado|copiar|repetitiv|toda semana|todo dia|notifica|lembrete|agendar/i, grupo: "operacao" }
  ],
  financeiro: [
    { id: "recorrencia", kw: /mensalidade|assinatura|recorr[eê]nte|\bplano\b|\bclube\b/i, grupo: "financeiro" },
    { id: "nota-fiscal", kw: /nota fiscal|\bnfe?\b|nfs-?e|emitir nota|emiss[aã]o/i, grupo: null },
    { id: "conciliacao", kw: /concilia|categoriz|onde (gasto|gasta|vai o dinheiro)|despesa|previs[aã]o de caixa|fluxo de caixa|fechar o m[eê]s|extrato/i, grupo: "financeiro" },
    { id: "cobranca", kw: /cobran[çc]|boleto|\bpix\b|inadimpl|receber|atras|d[eê]bito|devendo|r[eé]gua/i, grupo: "financeiro" }
  ]
};
function rotearSubFrente(categoria, textoLivre) {
  const subs = SUB_FRENTES_KW[categoria];
  const t = (textoLivre ?? "").toLowerCase();
  const achado = subs.find((s) => s.kw.test(t)) ?? subs[subs.length - 1];
  return { id: achado.id, grupo: achado.grupo };
}
function rotuloComplemento(jaUsa, categoria, subGrupo) {
  if (usaGrupo(jaUsa, "vendas") && subGrupo !== "vendas") return "o CRM que voc\xEA j\xE1 usa";
  if (usaGrupo(jaUsa, "operacao") && subGrupo !== "operacao") return "a automa\xE7\xE3o que voc\xEA j\xE1 usa (Make/Zapier)";
  if (usaGrupo(jaUsa, "planilha") && subGrupo !== "planilha" && (categoria === "operacao" || categoria === "financeiro" || categoria === "vendas"))
    return "a planilha que voc\xEA j\xE1 usa";
  if (usaGrupo(jaUsa, "iaGeral") && subGrupo !== "iaGeral" && (categoria === "operacao" || categoria === "atendimento"))
    return "a IA que voc\xEA j\xE1 usa (via API)";
  if (usaGrupo(jaUsa, "financeiro") && subGrupo !== "financeiro" && categoria !== "financeiro")
    return "a ferramenta de cobran\xE7a que voc\xEA j\xE1 usa";
  return "";
}
function classificarForma(args) {
  const { categoria, confianca, confiancaExplicacao, jaUsa, perfilExperiencia, time, volume, subGrupo } = args;
  if (confianca === "baixa") {
    return { forma: "validar", complementoLabel: "", formaMotivo: confiancaExplicacao };
  }
  const timeGrande = time === "6 a 20 pessoas" || time === "Mais de 20 pessoas";
  const volumeAlto = volume === "Mais de 50";
  if (subGrupo && usaGrupo(jaUsa, subGrupo)) {
    return {
      forma: "agente",
      complementoLabel: "",
      formaMotivo: "Voc\xEA j\xE1 usa uma ferramenta pra isso e o gargalo continua \u2014 o problema n\xE3o \xE9 a ferramenta, \xE9 a configura\xE7\xE3o pro seu processo."
    };
  }
  if (timeGrande && volumeAlto) {
    return {
      forma: "agente",
      complementoLabel: "",
      formaMotivo: "No seu volume de contatos e tamanho de time, ferramenta de prateleira trava na integra\xE7\xE3o e na manuten\xE7\xE3o."
    };
  }
  if (perfilExperiencia === "testou-falhou" && jaUsa.length >= 1) {
    return {
      forma: "agente",
      complementoLabel: "",
      formaMotivo: "Voc\xEA j\xE1 testou ferramentas e n\xE3o engatou. O pr\xF3ximo passo n\xE3o \xE9 outra ferramenta \u2014 \xE9 desenhar o agente pro seu caso."
    };
  }
  const comp = rotuloComplemento(jaUsa, categoria, subGrupo);
  if (comp) return { forma: "ferramenta-mais-complemento", complementoLabel: comp, formaMotivo: "" };
  return { forma: "uma-ferramenta", complementoLabel: "", formaMotivo: "" };
}
var INTRO_PERFIL = {
  iniciante: `Como \xE9 sua primeira vez com IA, comece pelo mais simples poss\xEDvel \u2014 resista ao impulso de montar tudo de uma vez. O objetivo das primeiras 2 semanas \xE9 entender a ferramenta funcionando de verdade, n\xE3o impressionar ningu\xE9m.

`,
  "testou-falhou": `J\xE1 que uma tentativa anterior n\xE3o deu certo, o ponto de virada aqui \xE9 escopo: rode um \xFAnico caso de uso ponta a ponta antes de expandir. A maioria das tentativas falha por tentar automatizar cedo demais, coisas demais.

`,
  "ja-usa": `Como voc\xEA j\xE1 usa alguma coisa hoje, foque em integra\xE7\xE3o e evolu\xE7\xE3o do que existe \u2014 n\xE3o em recome\xE7ar. Mapeie onde a ferramenta atual entrega valor e onde ela para, e trate esse gap como o pr\xF3ximo agente.

`
};
function contarMatches(p4, categoria) {
  if (!p4) return 0;
  return KEYWORDS[categoria].reduce((acc, re) => acc + (re.test(p4) ? 1 : 0), 0);
}
function analisarSinais(p4, categoriaOriginal, override) {
  const p4Trim = p4.trim();
  const p4Vago = p4Trim.length < 15;
  const matchesOriginal = contarMatches(p4Trim, categoriaOriginal);
  let melhorOutra = null;
  let melhorScore = 0;
  Object.keys(KEYWORDS).forEach((cat) => {
    if (cat === categoriaOriginal) return;
    const m = contarMatches(p4Trim, cat);
    if (m > melhorScore) {
      melhorScore = m;
      melhorOutra = cat;
    }
  });
  const p4MatchOutraCategoria = melhorOutra && melhorScore > matchesOriginal ? melhorOutra : null;
  return {
    p4MatchCategoriaOriginal: matchesOriginal,
    p4MatchOutraCategoria,
    p4Vago,
    overrideDisparado: override
  };
}
function classificarConfianca(sinais) {
  const { p4MatchCategoriaOriginal, p4MatchOutraCategoria, p4Vago, overrideDisparado } = sinais;
  if (overrideDisparado) {
    return {
      nivel: "baixa",
      explicacao: "Seu gargalo declarado difere do que o volume/time indica como prioridade real. Trate esse resultado como hip\xF3tese e valide antes de investir."
    };
  }
  if (p4MatchOutraCategoria) {
    return {
      nivel: "baixa",
      explicacao: `A tarefa que voc\xEA descreveu como mais consumidora aponta mais pra ${NOME_FRENTE[p4MatchOutraCategoria]} do que pro gargalo que marcou. Vale revalidar qual \xE9 a dor priorit\xE1ria.`
    };
  }
  if (p4MatchCategoriaOriginal >= 2) {
    return {
      nivel: "alta",
      explicacao: "Suas respostas convergem: gargalo declarado, tarefa que consome tempo e contexto do time apontam pra mesma frente."
    };
  }
  if (p4MatchCategoriaOriginal === 1 && !p4Vago) {
    return {
      nivel: "alta",
      explicacao: "A tarefa que consome seu tempo confirma o gargalo que voc\xEA marcou."
    };
  }
  if (p4Vago) {
    return {
      nivel: "media",
      explicacao: "Seu gargalo est\xE1 claro, mas a descri\xE7\xE3o da tarefa foi curta demais pra confirmar. Um bate-papo r\xE1pido resolve."
    };
  }
  return {
    nivel: "media",
    explicacao: "Sinais consistentes com o gargalo declarado, mas sem palavras-chave que confirmem por completo."
  };
}
function montarTitulo(categoria, confianca) {
  if (confianca === "alta") return NOME_AGENTE[categoria];
  if (confianca === "media") return `Prioridade: ${NOME_FRENTE[categoria]}`;
  return `Hip\xF3tese inicial: ${NOME_FRENTE[categoria]}`;
}
function montarSubtitulo(categoria, confianca) {
  const base = SUBTITULO[categoria];
  if (confianca === "baixa") {
    return "Suas respostas apontam pra mais de uma dire\xE7\xE3o. O caminho abaixo \xE9 uma hip\xF3tese pra validar \u2014 n\xE3o a resposta definitiva.";
  }
  return base;
}
function calcularResultado(respostas) {
  const perfil = classificarPerfil(respostas[1] ?? "");
  const p1 = respostas[2] ?? "";
  const p2 = respostas[3] ?? "";
  const p3 = respostas[4] ?? "";
  const p4 = respostas[5] ?? "";
  const p6 = respostas[6] ?? "";
  const jaUsaRaw = respostas[7] ?? "";
  const jaUsa = parseJaUsa(jaUsaRaw);
  const categoriaOriginal = P1_MAP[p1] ?? "atendimento";
  let categoria = categoriaOriginal;
  const timeMinimo = p2 === "S\xF3 eu" || p2 === "2 a 5 pessoas";
  const altaVolume = p3 === "Mais de 50";
  const overrideAtendimento = timeMinimo && altaVolume && categoriaOriginal !== "atendimento";
  if (overrideAtendimento) categoria = "atendimento";
  const perfilExperiencia = classificarExperiencia(jaUsaRaw);
  const avisoToolsGenericas = perfilExperiencia === "testou-falhou";
  const sinais = analisarSinais(p4, categoriaOriginal, overrideAtendimento);
  const { nivel: confianca, explicacao: confiancaExplicacao } = classificarConfianca(sinais);
  const sub = rotearSubFrente(categoria, `${p4} ${p6}`);
  const { forma, complementoLabel, formaMotivo } = classificarForma({
    categoria,
    confianca,
    confiancaExplicacao,
    jaUsa,
    perfilExperiencia,
    time: p2,
    volume: p3,
    subGrupo: sub.grupo
  });
  const conteudo = CONTEUDO[categoria];
  const contextoTime = {
    "S\xF3 eu": "Trabalhando sozinho, cada hora gasta em tarefa repetitiva \xE9 uma hora que voc\xEA n\xE3o gasta crescendo o neg\xF3cio",
    "2 a 5 pessoas": "Com um time enxuto de 2 a 5 pessoas, voc\xEA n\xE3o tem folga para alocar algu\xE9m s\xF3 nisso",
    "6 a 20 pessoas": "Com 6 a 20 pessoas, o custo de manter isso manual j\xE1 pesa na folha e no ritmo da equipe",
    "Mais de 20 pessoas": "Com mais de 20 pessoas, processos manuais viram gargalo de coordena\xE7\xE3o e erro em escala"
  };
  const contextoVolume = {
    "Menos de 10": "Mesmo com menos de 10 contatos por dia, a inconsist\xEAncia \xE9 o que custa cliente",
    "Entre 10 e 50": "Com 10 a 50 contatos por dia, voc\xEA j\xE1 est\xE1 no volume em que o manual come\xE7a a vazar",
    "Mais de 50": "Com mais de 50 contatos por dia, \xE9 humanamente imposs\xEDvel manter qualidade sem automa\xE7\xE3o"
  };
  const fraseTime = contextoTime[p2] ?? "";
  const fraseVolume = contextoVolume[p3] ?? "";
  const p4Curto = truncar(p4, 120);
  const nomeAgente = NOME_AGENTE[categoria];
  const nomeFrente = NOME_FRENTE[categoria];
  let porque = "";
  if (confianca === "alta") {
    const porqueBase = {
      atendimento: `O ponto cr\xEDtico est\xE1 na velocidade e consist\xEAncia do atendimento. ${fraseVolume || fraseTime || "Perder clientes por demora de resposta \xE9 resolv\xEDvel com automa\xE7\xE3o focada"}.`,
      vendas: `O gargalo est\xE1 no acompanhamento de oportunidades que j\xE1 existem. Leads sem resposta por mais de 24h t\xEAm chance de convers\xE3o drasticamente menor. ${fraseTime || fraseVolume || "Um agente de follow-up resolve isso sem depender de mem\xF3ria"}.`,
      operacao: `O tempo perdido em processos manuais internos \xE9 o maior freio de crescimento. ${fraseTime || fraseVolume || "Automatizar opera\xE7\xE3o libera horas semanais para o trabalho que precisa de voc\xEA"}.`,
      financeiro: `A falta de previsibilidade de caixa e a cobran\xE7a manual s\xE3o os maiores riscos para a sa\xFAde do neg\xF3cio. ${fraseTime || "Um agente financeiro resolve o operacional e d\xE1 clareza sobre o que entra e quando"}.`
    };
    const tarefa = p4Curto ? ` Voc\xEA destacou "${p4Curto}" como a tarefa que mais consome seu tempo \u2014 exatamente o tipo de coisa que o ${nomeAgente} elimina.` : "";
    porque = `${porqueBase[categoria]}${tarefa}`;
  } else if (confianca === "media") {
    const tarefa = p4Curto ? ` Voc\xEA destacou "${p4Curto}" como consumidor de tempo \u2014 trate essa como a primeira frente.` : "";
    porque = `Suas respostas apontam que a frente de ${nomeFrente} \xE9 onde vale come\xE7ar. ${fraseTime || fraseVolume || ""}${tarefa} Antes de nomear "agente X", vale rodar uma frente de automa\xE7\xE3o nessa dire\xE7\xE3o e ver o que aparece.`.trim();
  } else {
    if (overrideAtendimento) {
      const gargaloTexto = NOME_CATEGORIA[categoriaOriginal];
      porque = `Voc\xEA marcou ${gargaloTexto} como gargalo, mas com ${p2.toLowerCase()} e ${p3.toLowerCase()} contatos por dia, o atendimento provavelmente \xE9 o freio real antes de qualquer outra coisa. \xC9 uma hip\xF3tese \u2014 n\xE3o uma senten\xE7a. O caminho abaixo assume ${nomeFrente} como ponto de partida, mas o mais honesto aqui \xE9 validar isso numa conversa antes de escolher ferramenta.`;
    } else if (sinais.p4MatchOutraCategoria) {
      const outra = NOME_FRENTE[sinais.p4MatchOutraCategoria];
      porque = `Voc\xEA marcou ${NOME_CATEGORIA[categoriaOriginal]} como gargalo, mas a tarefa que descreveu ("${p4Curto}") soa mais como ${outra}. Isso n\xE3o invalida o diagn\xF3stico \u2014 s\xF3 indica que h\xE1 duas frentes ativas. O plano abaixo cobre ${nomeFrente}; ${outra} entra como segunda camada.`;
    } else {
      porque = `Suas respostas apontam pra ${nomeFrente}, mas com sinais fracos. Trate o conte\xFAdo abaixo como hip\xF3tese de trabalho \u2014 as ferramentas gerais que aparecem na sequ\xEAncia j\xE1 rendem enquanto voc\xEA valida o gargalo real.`;
    }
  }
  const metaTresMeses = metaValida(p6) ? truncar(p6, 220) : "";
  const pontePessoal = PONTE_META[categoria];
  const comoComecar = `${INTRO_PERFIL[perfilExperiencia]}${conteudo.comoComecar}`;
  return {
    categoria,
    titulo: montarTitulo(categoria, confianca),
    subtitulo: montarSubtitulo(categoria, confianca),
    ...conteudo,
    comoComecar,
    porque,
    avisoToolsGenericas,
    perfilExperiencia,
    perfil,
    perfilLabel: PERFIL_LABEL[perfil],
    jaUsa,
    metaTresMeses,
    pontePessoal,
    confianca,
    confiancaExplicacao,
    forma,
    complementoLabel,
    formaMotivo,
    subFrenteId: sub.id
  };
}

// src/lib/mcp/tools/calcular-diagnostico.ts
var PERFIL = z.enum([
  "Aut\xF4nomo ou freelancer \u2014 sou eu que fa\xE7o e entrego",
  "Consultor \u2014 presto servi\xE7o recorrente pra alguns clientes",
  "Ag\xEAncia \u2014 tenho um time entregando pra v\xE1rios clientes",
  "Empresa com time \u2014 opera\xE7\xE3o interna com funcion\xE1rios"
]);
var P1 = z.enum([
  "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
]);
var P2 = z.enum(["S\xF3 eu", "2 a 5 pessoas", "6 a 20 pessoas", "Mais de 20 pessoas"]);
var P3 = z.enum(["Menos de 10", "Entre 10 e 50", "Mais de 50"]);
var calcular_diagnostico_default = defineTool({
  name: "calcular_diagnostico",
  title: "Calcular diagn\xF3stico de agente de IA",
  description: "Roda o motor de recomenda\xE7\xE3o do Focus Diagn\xF3stico e retorna qual frente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) o neg\xF3cio deve priorizar, com justificativa, ferramentas recomendadas, guia de implementa\xE7\xE3o e um playbook.",
  inputSchema: {
    perfil: PERFIL.describe("Resposta da pergunta 1: como a pessoa trabalha."),
    gargalo_principal: P1.describe("Resposta da pergunta 2: onde est\xE1 o maior gargalo do neg\xF3cio."),
    tamanho_time: P2.describe("Resposta da pergunta 3: tamanho da opera\xE7\xE3o."),
    volume_contatos_dia: P3.describe("Resposta da pergunta 4: volume de contatos por dia."),
    tarefa_que_mais_consome: z.string().min(1).max(200).describe("Resposta da pergunta 5: tarefa manual que mais consome tempo (texto livre)."),
    meta_tres_meses: z.string().max(300).optional().describe("Resposta da pergunta 6 (opcional): o que mudaria no dia a dia daqui a 3 meses se der certo."),
    ja_usa: z.string().max(400).optional().describe(
      "Resposta da pergunta 7 (opcional): o que a pessoa j\xE1 usa hoje, separado por ponto e v\xEDrgula (ex.: 'ChatGPT no dia a dia; Um CRM'). Use 'Nada ainda' se for a primeira vez."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const respostas = {
      1: input.perfil,
      2: input.gargalo_principal,
      3: input.tamanho_time,
      4: input.volume_contatos_dia,
      5: input.tarefa_que_mais_consome,
      6: input.meta_tres_meses ?? "",
      7: input.ja_usa ?? ""
    };
    const resultado = calcularResultado(respostas);
    return {
      content: [{ type: "text", text: JSON.stringify(resultado, null, 2) }],
      structuredContent: { resultado }
    };
  }
});

// src/lib/mcp/tools/listar-ferramentas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var CATEGORIAS = ["atendimento", "vendas", "operacao", "financeiro"];
var GARGALO_POR_CATEGORIA = {
  atendimento: "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  vendas: "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  operacao: "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  financeiro: "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
};
var listar_ferramentas_default = defineTool2({
  name: "listar_ferramentas_por_categoria",
  title: "Listar ferramentas por categoria de agente",
  description: "Retorna as ferramentas recomendadas (nome, URL, descri\xE7\xE3o, plano) para uma categoria de agente de IA: atendimento, vendas, opera\xE7\xE3o ou financeiro.",
  inputSchema: {
    categoria: z2.enum(CATEGORIAS).describe("Categoria do agente de IA.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoria }) => {
    const resultado = calcularResultado({
      1: "Empresa com time \u2014 opera\xE7\xE3o interna com funcion\xE1rios",
      2: GARGALO_POR_CATEGORIA[categoria],
      3: "2 a 5 pessoas",
      4: "Entre 10 e 50",
      5: "tarefas repetitivas",
      6: "",
      7: "Nada ainda \u2014 seria minha primeira vez"
    });
    const payload = {
      categoria,
      titulo: resultado.titulo,
      ferramentas: resultado.ferramentas,
      ondeEncontrar: resultado.ondeEncontrar
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "focus-diagnostico-mcp",
  title: "Focus Diagn\xF3stico \u2014 Agentes de IA",
  version: "0.1.0",
  instructions: "Ferramentas do Focus Diagn\xF3stico. Use `calcular_diagnostico` para descobrir qual tipo de agente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) um neg\xF3cio deve priorizar, dadas as 5 respostas do diagn\xF3stico. Use `listar_ferramentas_por_categoria` para obter ferramentas recomendadas em uma categoria espec\xEDfica.",
  tools: [calcular_diagnostico_default, listar_ferramentas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
