// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/calcular-diagnostico.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { calcularResultado } from "npm:@/features/diagnostico/engine/recomendacao";
var P1 = z.enum([
  "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
]);
var P2 = z.enum(["S\xF3 eu", "2 a 5 pessoas", "6 a 20 pessoas", "Mais de 20 pessoas"]);
var P3 = z.enum(["Menos de 10", "Entre 10 e 50", "Mais de 50"]);
var P5 = z.enum(["Sim, testei mas n\xE3o deu certo", "N\xE3o, nunca tentei", "Uso algumas coisas soltas"]);
var calcular_diagnostico_default = defineTool({
  name: "calcular_diagnostico",
  title: "Calcular diagn\xF3stico de agente de IA",
  description: "Roda o motor de recomenda\xE7\xE3o do Focus Diagn\xF3stico e retorna qual tipo de agente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) o neg\xF3cio deve priorizar, com justificativa, ferramentas recomendadas e guia de implementa\xE7\xE3o.",
  inputSchema: {
    gargalo_principal: P1.describe("Resposta da pergunta 1: onde est\xE1 o maior gargalo do neg\xF3cio."),
    tamanho_time: P2.describe("Resposta da pergunta 2: tamanho do time."),
    volume_contatos_dia: P3.describe("Resposta da pergunta 3: volume de contatos por dia."),
    tarefa_que_mais_consome: z.string().min(1).max(200).describe("Resposta da pergunta 4: tarefa manual que mais consome tempo (texto livre)."),
    ja_tentou_automatizar: P5.describe("Resposta da pergunta 5: hist\xF3rico de tentativas com automa\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const respostas = {
      1: input.gargalo_principal,
      2: input.tamanho_time,
      3: input.volume_contatos_dia,
      4: input.tarefa_que_mais_consome,
      5: input.ja_tentou_automatizar
    };
    const resultado = calcularResultado(respostas);
    return {
      content: [{ type: "text", text: JSON.stringify(resultado, null, 2) }],
      structuredContent: { resultado }
    };
  }
});

// src/lib/mcp/tools/listar-ferramentas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { calcularResultado as calcularResultado2 } from "npm:@/features/diagnostico/engine/recomendacao";
var CATEGORIAS = ["atendimento", "vendas", "operacao", "financeiro"];
var GARGALO_POR_CATEGORIA = {
  atendimento: "Atendimento ao cliente \u2014 demoro para responder, perco gente no caminho",
  vendas: "Vendas e follow-up \u2014 esque\xE7o de cobrar resposta, perco oportunidade",
  operacao: "Opera\xE7\xE3o interna \u2014 processo manual, retrabalho, tarefa repetitiva",
  financeiro: "Financeiro \u2014 n\xE3o sei prever caixa, cobran\xE7a de cliente \xE9 manual"
};
var listar_ferramentas_default = defineTool2({
  name: "listar_ferramentas_por_categoria",
  title: "Listar ferramentas por categoria de agente",
  description: "Retorna as ferramentas recomendadas (nome, URL, descri\xE7\xE3o, plano) para uma categoria de agente de IA: atendimento, vendas, opera\xE7\xE3o ou financeiro.",
  inputSchema: {
    categoria: z2.enum(CATEGORIAS).describe("Categoria do agente de IA.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoria }) => {
    const resultado = calcularResultado2({
      1: GARGALO_POR_CATEGORIA[categoria],
      2: "2 a 5 pessoas",
      3: "Entre 10 e 50",
      4: "tarefas repetitivas",
      5: "N\xE3o, nunca tentei"
    });
    const payload = {
      categoria,
      titulo: resultado.titulo,
      ferramentas: resultado.ferramentas,
      ondeEncontrar: resultado.ondeEncontrar
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "focus-diagnostico-mcp",
  title: "Focus Diagn\xF3stico \u2014 Agentes de IA",
  version: "0.1.0",
  instructions: "Ferramentas do Focus Diagn\xF3stico. Use `calcular_diagnostico` para descobrir qual tipo de agente de IA (atendimento, vendas, opera\xE7\xE3o ou financeiro) um neg\xF3cio deve priorizar, dadas as 5 respostas do diagn\xF3stico. Use `listar_ferramentas_por_categoria` para obter ferramentas recomendadas em uma categoria espec\xEDfica.",
  tools: [calcular_diagnostico_default, listar_ferramentas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
